version = 1

SPDX-PackageName = "digit"
SPDX-PackageSupplier = "Will Reed <wreed@disroot.org>"

[[annotations]]
SPDX-FileCopyrightText = "2026 Will Reed <wreed@disroot.org>"
SPDX-License-Identifier = "LGPL-3.0-or-later WITH LGPL-3.0-linking-exception"
path = [
    "*.rst",
    "*.toml",
    "*.sdl",
    ".version",
    ".gitignore",
    ".editorconfig",
    "source/**",
    "misc/**",
    "aux/**",
    "makefile"
]
