SOURCES = \
	git/annotatedcommit.d \
	git/apply.d \
	git/attr.d \
	git/blame.d \
	git/blob.d \
	git/branch.d \
	git/buffer.d \
	git/cert.d \
	git/checkout.d \
	git/cherrypick.d \
	git/clone.d \
	git/commit.d \
	git/common.d \
	git/config.d \
	git/credential.d \
	git/credentialhelpers.d \
	git/describe.d \
	git/diff.d \
	git/email.d \
	git/errors.d \
	git/filter.d \
	git/graph.d \
	git/ignore.d \
	git/index.d \
	git/indexer.d \
	git/libversion.d \
	git/mailmap.d \
	git/merge.d \
	git/message.d \
	git/net.d \
	git/notes.d \
	git/object.d \
	git/odbbackend.d \
	git/odb.d \
	git/oidarray.d \
	git/oid.d \
	git/package.d \
	git/pack.d \
	git/patch.d \
	git/pathspec.d \
	git/proxy.d \
	git/rebase.d \
	git/refdb.d \
	git/reflog.d \
	git/refs.d \
	git/refspec.d \
	git/remote.d \
	git/repository.d \
	git/reset.d \
	git/revert.d \
	git/revparse.d \
	git/revwalk.d \
	git/signature.d \
	git/stash.d \
	git/status.d \
	git/strarray.d \
	git/submodule.d \
	git/tag.d \
	git/trace.d \
	git/transaction.d \
	git/transport.d \
	git/tree.d \
	git/types.d \
	git/worktree.d \
	git/sys/alloc.d \
	git/sys/commit.d \
	git/sys/commitgraph.d \
	git/sys/config.d \
	git/sys/credential.d \
	git/sys/diff.d \
	git/sys/email.d \
	git/sys/filter.d \
	git/sys/hashsig.d \
	git/sys/index.d \
	git/sys/mempack.d \
	git/sys/merge.d \
	git/sys/midx.d \
	git/sys/odbbackend.d \
	git/sys/openssl.d \
	git/sys/package.d \
	git/sys/path.d \
	git/sys/refdbbackend.d \
	git/sys/refs.d \
	git/sys/remote.d \
	git/sys/repository.d \
	git/sys/stream.d \
	git/sys/transport.d
